"""dialog model changes

Revision ID: 5d934b3df226
Revises: cd4f172a9627
Create Date: 2025-06-04 15:37:05.959711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d934b3df226'
down_revision = 'cd4f172a9627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('dialog', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('dialog_intern_id_fkey', 'dialog', type_='foreignkey')
    op.drop_constraint('dialog_manager_id_fkey', 'dialog', type_='foreignkey')
    op.create_foreign_key(None, 'dialog', 'user', ['recipient_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dialog', 'user', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_column('dialog', 'manager_id')
    op.drop_column('dialog', 'intern_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('intern_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dialog', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.create_foreign_key('dialog_manager_id_fkey', 'dialog', 'user', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('dialog_intern_id_fkey', 'dialog', 'user', ['intern_id'], ['id'], ondelete='SET NULL')
    op.drop_column('dialog', 'recipient_id')
    op.drop_column('dialog', 'sender_id')
    # ### end Alembic commands ###
