"""комментарий к миграции

Revision ID: cd4f172a9627
Revises: 
Create Date: 2025-06-01 01:39:31.188733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4f172a9627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('short_address', sa.String(length=100), nullable=False),
    sa.Column('contact_information', sa.String(length=100), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_address')
    )
    op.create_table('roadmap',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason_termination', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('referencepoint',
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('trigger_datetime', sa.DateTime(), nullable=False),
    sa.Column('check_datetime', sa.DateTime(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('completion_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('point_type', sa.String(), nullable=False),
    sa.Column('auto_closing', sa.Boolean(), nullable=False),
    sa.Column('order_execution', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templateroadmap',
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templatetest',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('time_respond', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=35), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_education_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('dialog',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_datetime', sa.DateTime(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('intern_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbackrequest',
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('reference_point_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_point_id'], ['referencepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_point_id')
    )
    op.create_table('invitationlink',
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('link_token', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token')
    )
    op.create_table('notification',
    sa.Column('user_feedback', sa.String(), nullable=True),
    sa.Column('referencepoint_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('need_feedback', sa.Boolean(), nullable=False),
    sa.Column('feedbacks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('servise_notes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['referencepoint_id'], ['referencepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencepoint_id')
    )
    op.create_table('templatequestion',
    sa.Column('templatetest_id', sa.Integer(), nullable=True),
    sa.Column('text_question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['templatetest_id'], ['templatetest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templatereferencepoint',
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('templateroadmap_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('point_type', sa.String(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('auto_closing', sa.Boolean(), nullable=False),
    sa.Column('order_execution', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['templateroadmap_id'], ['templateroadmap.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['templatetest.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test',
    sa.Column('referencepoint_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('time_respond', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['referencepoint_id'], ['referencepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('referencepoint_id')
    )
    op.create_table('userroadmap',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('user_answer', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('text_question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templatefeedbackrequest',
    sa.Column('reference_point_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_point_id'], ['templatereferencepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_point_id')
    )
    op.create_table('templatenotification',
    sa.Column('referencepoint_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('need_feedback', sa.Boolean(), nullable=False),
    sa.Column('feedbacks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('servise_notes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['referencepoint_id'], ['templatereferencepoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencepoint_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templatenotification')
    op.drop_table('templatefeedbackrequest')
    op.drop_table('question')
    op.drop_table('userroadmap')
    op.drop_table('test')
    op.drop_table('templatereferencepoint')
    op.drop_table('templatequestion')
    op.drop_table('notification')
    op.drop_table('invitationlink')
    op.drop_table('feedbackrequest')
    op.drop_table('dialog')
    op.drop_table('user')
    op.drop_table('templatetest')
    op.drop_table('templateroadmap')
    op.drop_table('referencepoint')
    op.drop_table('roadmap')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
